# Generated by Django 2.1 on 2019-07-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.PositiveIntegerField(choices=[(0, 'pending'), (1, 'completed')], default=0)),
                ('creation_date', models.DateField(default='2019-07-05')),
            ],
        ),
    ]
